version: "3"

services:
  proxy:
    volumes:
      # see https://github.com/matomo-org/matomo-nginx
      - ./proxy/conf/matomo.development.conf:/etc/nginx/conf.d/matomo.conf:ro
      - ./proxy/conf/grafana.development.conf:/etc/nginx/conf.d/grafana.conf:ro

  database:
    user: "${DATABASE_CONTAINER_UID}:${DATABASE_CONTAINER_GID}"
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - ${DB_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./database/data:/var/lib/mysql

  grafana:
    extra_hosts:
      - "host.docker.internal:host-gateway"
