version: "3"

services:
  proxy:
    volumes:
      - ./proxy/certbot/conf:/etc/letsencrypt
      - ./proxy/certbot/www:/var/www/certbot
      # see https://github.com/matomo-org/matomo-nginx
      - ./proxy/conf/matomo.production.conf:/etc/nginx/conf.d/matomo.conf:ro
    ports:
      - "443:443"

  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./proxy/certbot/conf:/etc/letsencrypt
      - ./proxy/certbot/www:/var/www/certbot
